### ISSUE TITLE
Cannot get encryption to work in chat.c

### ISSUE THREAD

**Issue by odessa2** [zeromq/zyre#569]
Hello,
I have been working with zyre for two month, but I can't get encryption to work, although draft-api is enabled on czmq and zyre.

How can I activate encryption? I cannot find anything in the documentation. It would be great to have chat.c in examples show how it is done, I cant be the only one who has this problem?

Can someone please help me?

Sincerely
odessa2

**Comment by bluca** [comment]
@wesyoung could you please have a look at this when you've got a sec?

**Comment by wesyoung** [comment]
ya, actually been diving into the zcert aspect of it this week- here's some python examples to look at:

https://github.com/wesyoung/pyzyre/blob/fix/certs/pyzyre/chat.py
https://github.com/wesyoung/pyzyre/blob/fix/certs/pyzyre/client/_task.py#L45

also take a look at the self tests because they're usually pretty solid when we make changes [so the changes are tested and pass):

https://github.com/zeromq/zyre/blob/master/src/zyre.c#L787
https://github.com/zeromq/czmq/blob/master/src/zgossip.c#L608

right now- you're basically doing two things- passing a cert to zyre which is just publishing the text of the public / secret key down to the sockets and applying them. the zgossip mech is very similar (check for the SET PUBLICKEY in both actors).

there isn't a lot of doc around this because we're still testing some of these ideas (make sure they scale etc) and building towards the "not just TLS but authentication via cert too" which isn't built in just yet (actually working through that problem now with the python code cited above, easier to test and prototype with, then move those patterns down into the C code). a lot of the crypto work is still DRAFT because it requires you to read down into the functions/headers a bit and follow the code... and IT MAY CHANGE- (esp the zgossip stuff because we need to move some of that to the code generation layer (gsl)).

make sense?

**Comment by odessa2** [comment]
Thank you @wesyoung , but I think I am missing something else, because zsys_has_curve() is always false.. Am I compiling something wrong? Do I need libdodium or is it possible to use the integrated NaCl?

**Comment by wesyoung** [comment]
i haven't tried with cmake- or with the `--without-libsodium -disable-static` before, the example build logs on opensuse look like this:

https://build.opensuse.org/package/live_build_log/network:messaging:zeromq:git-draft/zyre/xUbuntu_16.04/x86_64

my suggestion would be to remove those two flags to see how it works (either use libsodium or the default package from opensuse) just to see if it works- then build czmq master against that as well as zyre to see if you can get it working- then we can walk it backwards to see what's missing. might be libsodium- i forget of hand though.

what distro + ver/arch are you working with and how are you configuring zyre when you build it? same as your czmq 4.1 section?

**Comment by odessa2** [comment]
I'm on Ubunut 16.04 64bit.  I got it to work, it was a problem with LD_LIBRARY_PATH which loaded "old" librarys still on the system, also I recompiled with libsodium.
 
I was wondering, there has not been a release in over 13 month. Is there a roadmap for the next release, or who decides when a release of zyre is done?

**Comment by bluca** [comment]
You can get packages (including zyre) built from the latest master branch commit with draft enabled by adding this repository:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Agit-draft&package=libzyre-dev

**Comment by bluca** [comment]
those will include all required build dependencies, including libsodium etc

**Comment by odessa2** [comment]
@bluca  do you have information regarding my second question in https://github.com/zeromq/zyre/issues/569#issuecomment-367646834 ?

**Comment by bluca** [comment]
there is no roadmap - but the whole encryption stuff is still in flux so that will have to be finished at the very least

**Comment by wesyoung** [comment]
@odessa2 fwiw- we've been running it for a few months now (in a quasi-sandbox but with live data streams) and it seems somewhat stable- recently been testing it's intersection with czmq zcert and zap counterparts (for auth, not just anon TLS). while it seems to be running OK, there may be some odd issues when it comes to how you use certs and intersecting that with auth that are not well thought out yet. we've gotten it to work (eg: authenticating over zap to things like gossip) but we've also found some soft spots that i'm not 100% comfortable with.

i don't know that we can tag the entire TLS piece 'stable' unless it's ZAP counterparts have been fully tested, because i would think a lot of people would expect that (and if we found something odd in those upper layers, it may have implications on the TLS implementation itself).

the more eyeballs we get on this- finding out where it falls apart, probably the sooner it'll be ready for prime time (eg: enough ppl are complaining that it's still in draft for no good reason ;))
