### ISSUE TITLE
Problem: Zyre has a lot of new features in draft

### ISSUE THREAD

**Issue by sappo** [zeromq/zyre#574]
Zyre currently has a couple of features in draft which probably are in different maturity stages. To make it simpler for maintainers to bring on feature from draft into stable I suggest annotating the ifdef statement with a feature ID, e.g. 
```
#ifdef ZYRE_BUILD_DRAFT_API
//  DRAFT-API: Security
...
#endif

#ifdef ZYRE_BUILD_DRAFT_API
//  DRAFT-API: Public IP
...
#endif
```
what do you think @bluca @wesyoung @vyskocilm

**Comment by bluca** [comment]
Yeah sounds like a good idea

**Comment by wesyoung** [comment]
funny, was kinda think' the same thing (as i was fumbling through my various #ifdefs the other day). outside of those two tags- do you have any other considerations? i think i only have one real big thing to add in (and this may be more gossip than zyre) which is the zcertstore stuff that deals with security- i just wanted to run it in the wild for a few months to make sure things are solid before un-drafting it.

the other way to do this might be, rather than "security" or "public ip" but just adding maturity stages? 

* S1 - prototyping and feedback (eg: SET ADVERTISE..)
* S2 - QA (eg: SET PUBLIC KEY)

that way we're not keeping track of tags- per-say, but feature stages (which is the question i think you're really trying to answer?). maybe it's a combination of both- i could go either way- so whatever resonates with you guys. complete agree that it's getting hairy..

**Comment by bluca** [comment]
I think we should use issues to track stages - there can be milestones for example, where a feature X needs to solve Y issues to reach the "stable" milestone

**Comment by bluca** [comment]
the C4 RFC needs to be improved in this regard, I'll write a proposal as soon as I have time

**Comment by wesyoung** [comment]
sure thing- we can bat it around. prob a bunch of different ways to solve that, i'd like to error on something that wouldn't make @hintjens come back and kick our butts. :)

(none of us are really setup for project mgmt, and that's the beauty of it- but if we can come up with a @hintjens like solution to this, i think it'd be a neat accomplishment)

**Comment by sappo** [comment]
I like to keep it simple. If you like to use stages feel free to do so but as a first step I would be really happy to track ifdef blocks that belong together using a feature keyword. An additional issue no. is fine as well. The current workflow is for the author(s) of the new draft API to decide when its ready to become stable.

Regarding new features I have leader election in zyre groups lined up which has been my hackathon project :)

**Comment by bluca** [comment]
Yes anything else aside, tagging ifdefs is a good idea regardless of what else we can do

**Comment by wesyoung** [comment]
wfm- i'm currently messing with zgossip ttls and heartbeats- the security stuff seems somewhat stable but i'll go through both and PR the tags sometime in the next week.

**Comment by wesyoung** [comment]
something something something... "got lost in the matrix..." sorry. :(

i've been running the bulk of this on the backend last few months though, seems somewhat stable so maybe we can start bleeding the features into stable over the next few months...
