### ISSUE TITLE
freen not defined

### ISSUE THREAD

**Issue by leochan2009** [zeromq/zyre#611]
Hi, 
I am trying to compile the zyre with enable_draft=ON at the ubuntu 18.04 with gcc 7.3 
here is the error code i received:

> /home/user/Desktop/Work/ZyreAuthentification/build-framework-Qt_5_9_5_Package-Debug/ThirdParty/zyre-master/src/zyre.c: In function ‘zyre_test’:
/home/user/Desktop/Work/ZyreAuthentification/build-framework-Qt_5_9_5_Package-Debug/ThirdParty/zyre-master/src/zyre.c:901:13: warning: implicit declaration of function ‘freen’; did you mean ‘free’? [-Wimplicit-function-declaration]
             freen (hostname);
             ^~~~~
             free
[ 33%] Built target zyre_objects
[ 37%] Linking C shared library libzyre.so
[ 37%] Built target zyre
[ 41%] Linking C executable ztester_gossip
libzyre.so.2.0.1: undefined reference to `freen'

**Comment by bluca** [comment]
Rather than building your own, consider using the prebuilt packages.

For latest git master:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Agit-draft&package=libzyre-dev

For latest release:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-draft&package=libzyre-dev

**Comment by sappo** [comment]
Could you please describe the command chain that lead to the error.

Am Di., 6. Nov. 2018, 22:42 hat leochan2009 <notifications@github.com>
geschrieben:
