### ISSUE TITLE
Missing zyre_peer_name() in public API

### ISSUE THREAD

**Issue by jesseoff** [zeromq/zyre#649]
There is no public API function for retreiving the name of a given peer.  It looks like its implemented in the api protocol as a "PEER NAME" call, but there is no public zyre.h function for it.

**Comment by sthoduka** [comment]
related issues/PRs:
https://github.com/zeromq/zyre/issues/297
https://github.com/zeromq/zyre/pull/298
https://github.com/zeromq/zyre/commit/777c78aebd95911f715876a3ed5935d1053a079b#diff-e857acc9d05541b3024a5b4f009fa3b9

to summarize, this was added and later removed because you get the names of the peers anyway with the 'ENTER' message.
